### ISSUE TITLE
[meta] Missing features/problems for MVP-FFM

### ISSUE THREAD

**Issue by benbender** [kiebitz-oss/services-inoeg#4]
- [x] GetAppointmentsByZipCodeForm: can be queried max 2 days into the future, should be configurable: https://github.com/kiebitz-oss/services-inoeg/blob/520752cad4f1cdb70a419f9a806cb3117791bde1/forms/appointments.go#L594
- [x] AppointmentPropertiesForm : vaccines should be configureable: https://github.com/kiebitz-oss/services-inoeg/blob/520752cad4f1cdb70a419f9a806cb3117791bde1/forms/appointments.go#L679
- [x] GetProviderAppointmentsDataForm: can be queried max 14 days into the future, should be configurable: https://github.com/kiebitz-oss/services-inoeg/blob/520752cad4f1cdb70a419f9a806cb3117791bde1/forms/appointments.go#L641
- [x] aggregated getAppointments: after kiebitz-oss/services#28 is finished. Related kiebitz-oss/vanellus-inoeg#13.
- [x] add getProvidersByZip()-endpoint
- [x] make information about accessibility public
- [x] #12 
- [x] #13 

This issue can and should be extended as I don't have a complete overview on the services-code.

**Comment by tauli** [comment]
@benbender können wir das ticket schließen, oder fehlt hier noch was?

**Comment by benbender** [comment]
@tauli ich mach es erstmal zu - vmtl fällt die kommenden Tage noch was auf, aber dann mach ich es wieder auf.
